!u8i = !cir.int<u, 8>
#fn_attr = #cir<extra({})>
#fn_attr1 = #cir<extra({nothrow = #cir.nothrow})>
#fn_attr2 = #cir<extra({nothrow = #cir.nothrow, uwtable = #cir.uwtable<async>})>
!rec_std3A3Aios_base3A3AInit = !cir.record<class "std::ios_base::Init" padded {!u8i} #cir.record.decl.ast>
module @"/home/adrianj/IOOptCompilerPass/combined-tests/end_to_end_main.cpp" attributes {cir.global_ctors = [#cir.global_ctor<"__cxx_global_var_init", 65535>], cir.module_asm = [], cir.type_size_info = #cir.type_size_info<char = 8, int = 32, size_t = 64>, cir.uwtable = #cir.uwtable<async>, dlti.dl_spec = #dlti.dl_spec<!llvm.ptr<270> = dense<32> : vector<4xi64>, !llvm.ptr<271> = dense<32> : vector<4xi64>, !llvm.ptr<272> = dense<64> : vector<4xi64>, i64 = dense<64> : vector<2xi64>, i128 = dense<128> : vector<2xi64>, f80 = dense<128> : vector<2xi64>, !llvm.ptr = dense<64> : vector<4xi64>, i1 = dense<8> : vector<2xi64>, i8 = dense<8> : vector<2xi64>, i16 = dense<16> : vector<2xi64>, i32 = dense<32> : vector<2xi64>, f16 = dense<16> : vector<2xi64>, f64 = dense<64> : vector<2xi64>, f128 = dense<128> : vector<2xi64>, "dlti.endianness" = "little", "dlti.mangling_mode" = "e", "dlti.legal_int_widths" = array<i32: 8, 16, 32, 64>, "dlti.stack_alignment" = 128 : i64>, llvm.module_asm = [], llvm.target_triple = "x86_64-unknown-linux-gnu"} {
  llvm.mlir.global private constant @__const.main.buffer("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\00") {addr_space = 0 : i32} loc(#loc49)
  llvm.mlir.global external @__dso_handle() {addr_space = 0 : i32} : i8 loc(#loc50)
  llvm.func @__cxa_atexit(!llvm.ptr, !llvm.ptr, !llvm.ptr) attributes {cir.extra_attrs = #fn_attr, global_visibility = #cir<visibility default>, sym_visibility = "private"} loc(#loc64)
  llvm.func @_ZNSt8ios_base4InitC1Ev(!llvm.ptr) attributes {cir.extra_attrs = #fn_attr, cxx_special_member = #cir.cxx_ctor<!rec_std3A3Aios_base3A3AInit, default>, global_visibility = #cir<visibility default>, sym_visibility = "private"} loc(#loc65)
  llvm.func @_ZNSt8ios_base4InitD1Ev(!llvm.ptr) attributes {cir.extra_attrs = #fn_attr1, cxx_special_member = #cir.cxx_dtor<!rec_std3A3Aios_base3A3AInit>, global_visibility = #cir<visibility default>, sym_visibility = "private"} loc(#loc66)
  llvm.mlir.global internal @_ZStL8__ioinit(#llvm.zero) {addr_space = 0 : i32, alignment = 1 : i64, dso_local} : !llvm.struct<"class.std::ios_base::Init", (i8)> loc(#loc50)
  llvm.func internal @__cxx_global_var_init() attributes {cir.extra_attrs = #fn_attr, global_visibility = #cir<visibility default>, sym_visibility = "private"} {
    %0 = llvm.mlir.addressof @_ZStL8__ioinit : !llvm.ptr loc(#loc50)
    llvm.call @_ZNSt8ios_base4InitC1Ev(%0) : (!llvm.ptr) -> () loc(#loc4)
    %1 = llvm.mlir.addressof @_ZStL8__ioinit : !llvm.ptr loc(#loc50)
    %2 = llvm.mlir.addressof @_ZNSt8ios_base4InitD1Ev : !llvm.ptr loc(#loc50)
    %3 = llvm.bitcast %2 : !llvm.ptr to !llvm.ptr loc(#loc50)
    %4 = llvm.bitcast %1 : !llvm.ptr to !llvm.ptr loc(#loc50)
    %5 = llvm.mlir.addressof @__dso_handle : !llvm.ptr loc(#loc50)
    llvm.call @__cxa_atexit(%3, %4, %5) : (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> () loc(#loc50)
    llvm.return loc(#loc50)
  } loc(#loc71)
  llvm.func @open(!llvm.ptr, i32, ...) -> i32 attributes {cir.extra_attrs = #fn_attr, global_visibility = #cir<visibility default>, sym_visibility = "private"} loc(#loc67)
  llvm.mlir.global private constant @".str"("output_test.txt\00") {addr_space = 0 : i32, alignment = 1 : i64, dso_local} loc(#loc8)
  llvm.func @write(i32, !llvm.ptr, i64) -> i64 attributes {cir.extra_attrs = #fn_attr, global_visibility = #cir<visibility default>, sym_visibility = "private"} loc(#loc68)
  llvm.func @_Z12write_footeri(i32) attributes {cir.extra_attrs = #fn_attr, global_visibility = #cir<visibility default>, sym_visibility = "private"} loc(#loc69)
  llvm.func @close(i32) -> i32 attributes {cir.extra_attrs = #fn_attr, global_visibility = #cir<visibility default>, sym_visibility = "private"} loc(#loc70)
  llvm.func @main() -> i32 attributes {cir.extra_attrs = #fn_attr2, dso_local, global_visibility = #cir<visibility default>, no_inline, optimize_none} {
    %0 = llvm.mlir.constant(1 : index) : i64 loc(#loc51)
    %1 = llvm.alloca %0 x i32 {alignment = 4 : i64} : (i64) -> !llvm.ptr loc(#loc51)
    %2 = llvm.mlir.constant(1 : index) : i64 loc(#loc15)
    %3 = llvm.alloca %2 x i32 {alignment = 4 : i64} : (i64) -> !llvm.ptr loc(#loc15)
    %4 = llvm.mlir.constant(1 : index) : i64 loc(#loc52)
    %5 = llvm.alloca %4 x i32 {alignment = 4 : i64} : (i64) -> !llvm.ptr loc(#loc52)
    %6 = llvm.mlir.constant(1 : index) : i64 loc(#loc49)
    %7 = llvm.alloca %6 x !llvm.array<37 x i8> {alignment = 16 : i64} : (i64) -> !llvm.ptr loc(#loc49)
    %8 = llvm.mlir.addressof @".str" : !llvm.ptr loc(#loc8)
    %9 = llvm.getelementptr %8[0] : (!llvm.ptr) -> !llvm.ptr, i8 loc(#loc8)
    %10 = llvm.mlir.constant(1 : i32) : i32 loc(#loc18)
    %11 = llvm.mlir.constant(64 : i32) : i32 loc(#loc19)
    %12 = llvm.or %10, %11 : i32 loc(#loc53)
    %13 = llvm.mlir.constant(512 : i32) : i32 loc(#loc20)
    %14 = llvm.or %12, %13 : i32 loc(#loc54)
    %15 = llvm.mlir.constant(420 : i32) : i32 loc(#loc21)
    %16 = llvm.call @open(%9, %14, %15) vararg(!llvm.func<i32 (ptr, i32, ...)>) : (!llvm.ptr, i32, i32) -> i32 loc(#loc22)
    llvm.store %16, %5 {alignment = 4 : i64} : i32, !llvm.ptr loc(#loc52)
    llvm.br ^bb1 loc(#loc55)
  ^bb1:  // pred: ^bb0
    %17 = llvm.load %5 {alignment = 4 : i64} : !llvm.ptr -> i32 loc(#loc25)
    %18 = llvm.mlir.constant(0 : i32) : i32 loc(#loc26)
    %19 = llvm.icmp "slt" %17, %18 : i32 loc(#loc56)
    llvm.cond_br %19, ^bb2, ^bb3 loc(#loc57)
  ^bb2:  // pred: ^bb1
    %20 = llvm.mlir.constant(1 : i32) : i32 loc(#loc24)
    llvm.store %20, %3 {alignment = 4 : i64} : i32, !llvm.ptr loc(#loc57)
    %21 = llvm.load %3 {alignment = 4 : i64} : !llvm.ptr -> i32 loc(#loc57)
    llvm.return %21 : i32 loc(#loc57)
  ^bb3:  // pred: ^bb1
    llvm.br ^bb4 loc(#loc24)
  ^bb4:  // pred: ^bb3
    %22 = llvm.mlir.addressof @__const.main.buffer : !llvm.ptr loc(#loc49)
    %23 = llvm.mlir.constant(37 : i32) : i32 loc(#loc49)
    "llvm.intr.memcpy"(%7, %22, %23) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i32) -> () loc(#loc49)
    llvm.br ^bb5 loc(#loc58)
  ^bb5:  // pred: ^bb4
    %24 = llvm.mlir.constant(0 : i32) : i32 loc(#loc14)
    llvm.store %24, %1 {alignment = 4 : i64} : i32, !llvm.ptr loc(#loc51)
    llvm.br ^bb6 loc(#loc58)
  ^bb6:  // 2 preds: ^bb5, ^bb10
    %25 = llvm.load %1 {alignment = 4 : i64} : !llvm.ptr -> i32 loc(#loc30)
    %26 = llvm.mlir.constant(10 : i32) : i32 loc(#loc31)
    %27 = llvm.icmp "slt" %25, %26 : i32 loc(#loc59)
    llvm.cond_br %27, ^bb7, ^bb11 loc(#loc59)
  ^bb7:  // pred: ^bb6
    llvm.br ^bb8 loc(#loc60)
  ^bb8:  // pred: ^bb7
    %28 = llvm.load %5 {alignment = 4 : i64} : !llvm.ptr -> i32 loc(#loc33)
    %29 = llvm.load %1 {alignment = 4 : i64} : !llvm.ptr -> i32 loc(#loc34)
    %30 = llvm.sext %29 : i32 to i64 loc(#loc34)
    %31 = llvm.getelementptr %7[0, %30] : (!llvm.ptr, i64) -> !llvm.ptr, !llvm.array<37 x i8> loc(#loc35)
    %32 = llvm.bitcast %31 : !llvm.ptr to !llvm.ptr loc(#loc61)
    %33 = llvm.mlir.constant(1 : i32) : i32 loc(#loc38)
    %34 = llvm.sext %33 : i32 to i64 loc(#loc38)
    %35 = llvm.call @write(%28, %32, %34) : (i32, !llvm.ptr, i64) -> i64 loc(#loc39)
    llvm.br ^bb9 loc(#loc29)
  ^bb9:  // pred: ^bb8
    llvm.br ^bb10 loc(#loc29)
  ^bb10:  // pred: ^bb9
    %36 = llvm.mlir.constant(2 : i32) : i32 loc(#loc40)
    %37 = llvm.load %1 {alignment = 4 : i64} : !llvm.ptr -> i32 loc(#loc41)
    %38 = llvm.add %37, %36 overflow<nsw> : i32 loc(#loc41)
    llvm.store %38, %1 {alignment = 4 : i64} : i32, !llvm.ptr loc(#loc62)
    llvm.br ^bb6 loc(#loc58)
  ^bb11:  // pred: ^bb6
    llvm.br ^bb12 loc(#loc29)
  ^bb12:  // pred: ^bb11
    %39 = llvm.load %5 {alignment = 4 : i64} : !llvm.ptr -> i32 loc(#loc43)
    llvm.call @_Z12write_footeri(%39) : (i32) -> () loc(#loc44)
    %40 = llvm.load %5 {alignment = 4 : i64} : !llvm.ptr -> i32 loc(#loc45)
    %41 = llvm.call @close(%40) : (i32) -> i32 loc(#loc46)
    %42 = llvm.mlir.constant(0 : i32) : i32 loc(#loc47)
    llvm.store %42, %3 {alignment = 4 : i64} : i32, !llvm.ptr loc(#loc63)
    %43 = llvm.load %3 {alignment = 4 : i64} : !llvm.ptr -> i32 loc(#loc63)
    llvm.return %43 : i32 loc(#loc63)
  } loc(#loc72)
  llvm.func @_GLOBAL__sub_I_end_to_end_main.cpp() attributes {cir.extra_attrs = #fn_attr, global_visibility = #cir<visibility default>, sym_visibility = "private"} {
    llvm.call @__cxx_global_var_init() : () -> () loc(#loc50)
    llvm.return loc(#loc)
  } loc(#loc73)
  llvm.mlir.global appending constant @llvm.global_ctors() {addr_space = 0 : i32} : !llvm.array<1 x struct<(i32, ptr, ptr)>> {
    %0 = llvm.mlir.undef : !llvm.array<1 x struct<(i32, ptr, ptr)>> loc(#loc)
    %1 = llvm.mlir.undef : !llvm.struct<(i32, ptr, ptr)> loc(#loc)
    %2 = llvm.mlir.constant(65535 : i32) : i32 loc(#loc)
    %3 = llvm.mlir.addressof @__cxx_global_var_init : !llvm.ptr loc(#loc)
    %4 = llvm.mlir.zero : !llvm.ptr loc(#loc)
    %5 = llvm.insertvalue %2, %1[0] : !llvm.struct<(i32, ptr, ptr)>  loc(#loc)
    %6 = llvm.insertvalue %3, %5[1] : !llvm.struct<(i32, ptr, ptr)>  loc(#loc)
    %7 = llvm.insertvalue %4, %6[2] : !llvm.struct<(i32, ptr, ptr)>  loc(#loc)
    %8 = llvm.insertvalue %7, %0[0] : !llvm.array<1 x struct<(i32, ptr, ptr)>>  loc(#loc)
    llvm.return %8 : !llvm.array<1 x struct<(i32, ptr, ptr)>> loc(#loc)
  } loc(#loc)
} loc(#loc)
#di_file = #llvm.di_file<"iostream" in "/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11">
#di_file1 = #llvm.di_file<"ios_base.h" in "/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits">
#di_file2 = #llvm.di_file<"end_to_end_main.cpp" in "/home/adrianj/IOOptCompilerPass/combined-tests">
#di_file3 = #llvm.di_file<"fcntl.h" in "/usr/include">
#di_file4 = #llvm.di_file<"unistd.h" in "/usr/include">
#di_file5 = #llvm.di_file<"end_to_end_main.cpp" in "">
#di_subroutine_type = #llvm.di_subroutine_type<callingConvention = DW_CC_normal>
#loc = loc("/home/adrianj/IOOptCompilerPass/combined-tests/end_to_end_main.cpp":0:0)
#loc1 = loc("end_to_end_main.cpp":13:5)
#loc2 = loc("end_to_end_main.cpp":13:21)
#loc3 = loc("/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/iostream":74:3)
#loc4 = loc("/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/iostream":74:25)
#loc5 = loc("/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/ios_base.h":630:7)
#loc6 = loc("/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/ios_base.h":631:7)
#loc7 = loc("/usr/include/fcntl.h":209:1)
#loc8 = loc("end_to_end_main.cpp":10:19)
#loc9 = loc("/usr/include/unistd.h":378:1)
#loc10 = loc("end_to_end_main.cpp":7:1)
#loc11 = loc("/usr/include/unistd.h":358:1)
#loc12 = loc("end_to_end_main.cpp":9:1)
#loc13 = loc("end_to_end_main.cpp":18:10)
#loc14 = loc("end_to_end_main.cpp":18:18)
#loc15 = loc("end_to_end_main.cpp":28:1)
#loc16 = loc("end_to_end_main.cpp":10:5)
#loc17 = loc("end_to_end_main.cpp":10:72)
#loc18 = loc("end_to_end_main.cpp":10:38)
#loc19 = loc("end_to_end_main.cpp":10:49)
#loc20 = loc("end_to_end_main.cpp":10:59)
#loc21 = loc("end_to_end_main.cpp":10:68)
#loc22 = loc("end_to_end_main.cpp":10:14)
#loc23 = loc("end_to_end_main.cpp":11:5)
#loc24 = loc("end_to_end_main.cpp":11:24)
#loc25 = loc("end_to_end_main.cpp":11:9)
#loc26 = loc("end_to_end_main.cpp":11:14)
#loc27 = loc("end_to_end_main.cpp":11:17)
#loc28 = loc("end_to_end_main.cpp":18:5)
#loc29 = loc("end_to_end_main.cpp":20:5)
#loc30 = loc("end_to_end_main.cpp":18:21)
#loc31 = loc("end_to_end_main.cpp":18:25)
#loc32 = loc("end_to_end_main.cpp":18:37)
#loc33 = loc("end_to_end_main.cpp":19:15)
#loc34 = loc("end_to_end_main.cpp":19:27)
#loc35 = loc("end_to_end_main.cpp":19:20)
#loc36 = loc("end_to_end_main.cpp":19:19)
#loc37 = loc("end_to_end_main.cpp":19:28)
#loc38 = loc("end_to_end_main.cpp":19:31)
#loc39 = loc("end_to_end_main.cpp":19:9)
#loc40 = loc("end_to_end_main.cpp":18:34)
#loc41 = loc("end_to_end_main.cpp":18:31)
#loc42 = loc("end_to_end_main.cpp":18:29)
#loc43 = loc("end_to_end_main.cpp":24:18)
#loc44 = loc("end_to_end_main.cpp":24:5)
#loc45 = loc("end_to_end_main.cpp":26:11)
#loc46 = loc("end_to_end_main.cpp":26:5)
#loc47 = loc("end_to_end_main.cpp":27:12)
#loc48 = loc("end_to_end_main.cpp":27:5)
#di_compile_unit = #llvm.di_compile_unit<id = distinct[0]<>, sourceLanguage = DW_LANG_C, file = #di_file2, producer = "MLIR", isOptimized = true, emissionKind = LineTablesOnly>
#di_subprogram = #llvm.di_subprogram<scope = #di_file, name = "__cxa_atexit", linkageName = "__cxa_atexit", file = #di_file, line = 74, scopeLine = 74, subprogramFlags = Optimized, type = #di_subroutine_type>
#di_subprogram1 = #llvm.di_subprogram<scope = #di_file1, name = "_ZNSt8ios_base4InitC1Ev", linkageName = "_ZNSt8ios_base4InitC1Ev", file = #di_file1, line = 630, scopeLine = 630, subprogramFlags = Optimized, type = #di_subroutine_type>
#di_subprogram2 = #llvm.di_subprogram<scope = #di_file1, name = "_ZNSt8ios_base4InitD1Ev", linkageName = "_ZNSt8ios_base4InitD1Ev", file = #di_file1, line = 631, scopeLine = 631, subprogramFlags = Optimized, type = #di_subroutine_type>
#di_subprogram3 = #llvm.di_subprogram<scope = #di_file3, name = "open", linkageName = "open", file = #di_file3, line = 209, scopeLine = 209, subprogramFlags = Optimized, type = #di_subroutine_type>
#di_subprogram4 = #llvm.di_subprogram<scope = #di_file4, name = "write", linkageName = "write", file = #di_file4, line = 378, scopeLine = 378, subprogramFlags = Optimized, type = #di_subroutine_type>
#di_subprogram5 = #llvm.di_subprogram<scope = #di_file5, name = "_Z12write_footeri", linkageName = "_Z12write_footeri", file = #di_file5, line = 7, scopeLine = 7, subprogramFlags = Optimized, type = #di_subroutine_type>
#di_subprogram6 = #llvm.di_subprogram<scope = #di_file4, name = "close", linkageName = "close", file = #di_file4, line = 358, scopeLine = 358, subprogramFlags = Optimized, type = #di_subroutine_type>
#loc49 = loc(fused[#loc1, #loc2])
#loc50 = loc(fused[#loc3, #loc4])
#loc51 = loc(fused[#loc13, #loc14])
#loc52 = loc(fused[#loc16, #loc17])
#loc53 = loc(fused[#loc18, #loc19])
#loc54 = loc(fused[#loc18, #loc20])
#loc55 = loc(fused[#loc23, #loc24])
#loc56 = loc(fused[#loc25, #loc26])
#loc57 = loc(fused[#loc27, #loc24])
#loc58 = loc(fused[#loc28, #loc29])
#loc59 = loc(fused[#loc30, #loc31])
#loc60 = loc(fused[#loc32, #loc29])
#loc61 = loc(fused[#loc36, #loc37])
#loc62 = loc(fused[#loc42, #loc40])
#loc63 = loc(fused[#loc48, #loc47])
#di_subprogram7 = #llvm.di_subprogram<id = distinct[1]<>, compileUnit = #di_compile_unit, scope = #di_file, name = "__cxx_global_var_init", linkageName = "__cxx_global_var_init", file = #di_file, line = 74, scopeLine = 74, subprogramFlags = "Definition|Optimized", type = #di_subroutine_type>
#di_subprogram8 = #llvm.di_subprogram<id = distinct[2]<>, compileUnit = #di_compile_unit, scope = #di_file5, name = "main", linkageName = "main", file = #di_file5, line = 9, scopeLine = 9, subprogramFlags = "Definition|Optimized", type = #di_subroutine_type>
#di_subprogram9 = #llvm.di_subprogram<id = distinct[3]<>, compileUnit = #di_compile_unit, scope = #di_file2, name = "_GLOBAL__sub_I_end_to_end_main.cpp", linkageName = "_GLOBAL__sub_I_end_to_end_main.cpp", file = #di_file2, subprogramFlags = "Definition|Optimized", type = #di_subroutine_type>
#loc64 = loc(fused<#di_subprogram>[#loc3])
#loc65 = loc(fused<#di_subprogram1>[#loc5])
#loc66 = loc(fused<#di_subprogram2>[#loc6])
#loc67 = loc(fused<#di_subprogram3>[#loc7])
#loc68 = loc(fused<#di_subprogram4>[#loc9])
#loc69 = loc(fused<#di_subprogram5>[#loc10])
#loc70 = loc(fused<#di_subprogram6>[#loc11])
#loc71 = loc(fused<#di_subprogram7>[#loc3])
#loc72 = loc(fused<#di_subprogram8>[#loc12])
#loc73 = loc(fused<#di_subprogram9>[#loc])
